# Generated by Django 3.0.6 on 2020-07-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Models',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(),
        ),
    ]
